export const elements: string[][] = [
  ['leche', 'pan', 'huevos', 'jugo'],
  ['pan', 'huevos', 'café', 'arroz'],
  ['hamburguesa', 'leche', 'azúcar', 'huevos'],
  ['manzana', 'leche', 'pan', 'huevos', 'jugo'],
  ['manzana', 'pan', 'huevos', 'café'],
  ['manzana', 'leche', 'azúcar', 'huevos'],
  ['hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['manzana', 'plátano', 'naranja', 'pera'],
  ['hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['carne', 'pimienta', 'sal', 'cebolla'],
  ['yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'jamón', 'queso', 'tomate'],
  ['papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['atún', 'arroz', 'leche', 'azúcar', 'huevo', 'maíz'],
  ['hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['manzana', 'pera', 'durazno', 'uva'],
  ['pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['fideos', 'leche', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['helado', 'chocolate', 'nuez', 'caramelo'],
  ['hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['café', 'leche', 'azúcar', 'canela'],
  ['naranja', 'zanahoria', 'jengibre', 'limón'],
  ['arroz', 'frijoles', 'plátano', 'queso'],
  ['yogur', 'frutilla', 'avena', 'miel'],
  ['pescado', 'limón', 'sal', 'pimienta'],
  ['brócoli', 'leche', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['avena', 'leche', 'miel', 'almendras', 'pan'],
  ['hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['yogur', 'frutilla', 'avena', 'miel'],
  ['pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pimiento', 'leche', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['espinacas', 'leche', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['fresa', 'plátano', 'yogur', 'miel'],
  ['maní', 'pasas', 'nuez', 'almendra'],
  ['yogur', 'frutilla', 'avena', 'miel'],
  ['té', 'limón', 'miel', 'menta'],
  ['hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['papas', 'leche', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pasta', 'atún', 'tomate', 'aceitunas'],
  ['pollo', 'leche', 'azúcar', 'limón', 'ajo', 'romero'],
  ['yogur', 'frutilla', 'avena', 'miel'],
  ['frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['hamburguesa', 'leche', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['manzana', 'nuez', 'miel', 'canela'],
  ['yogur', 'frutilla', 'avena', 'miel'],
  ['pavo', 'pan', 'lechuga', 'tomate'],
  ['pimiento', 'cebolla', 'tomate', 'ajo'],
  ['fresa', 'leche', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['leche', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['calabaza', 'zanahoria', 'batata', 'maíz'],
  ['garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pasta', 'atún', 'tomate', 'aceitunas'],
  ['hamburguesa', 'leche', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['frijoles', 'arroz', 'plátano', 'queso'],
  ['nuez', 'miel', 'avena', 'leche', 'azúcar', 'canela', 'pan'],
  ['nuez', 'miel', 'avena', 'canela', 'leche', 'azúcar', 'pan'],
  ['hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['manzana', 'leche', 'azúcar', 'nuez', 'miel', 'canela'],
  ['manzana', 'leche', 'azúcar', 'nuez', 'miel', 'canela'],
  ['manzana', 'leche', 'azúcar', 'nuez', 'miel', 'canela'],
  //   // Más productos...
];
