export const elements: string[][] = [
  ['pan', 'leche' , 'arroz', 'huevos', 'jugo'],
  ['pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pollo', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'pollo', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'pollo', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'pollo', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'pollo', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pollo', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pollo', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'pollo', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'pollo', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'pollo', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pollo', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'pollo', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'pollo', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'pollo', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pollo', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pollo', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pollo', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'pollo', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'pollo', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'pollo', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'pollo', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'pollo', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'pollo', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pollo', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'pollo', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'pollo', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'pollo', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pan', 'jamón', 'queso', 'tomate'],
  ['pan', 'papa', 'zanahoria', 'brócoli', 'coliflor'],
  ['pan', 'atún', 'arroz', 'leche' , 'arroz', 'azúcar', 'huevo', 'maíz'],
  ['pan', 'hamburguesa', 'lechuga', 'tomate', 'pepino', 'aceitunas'],
  ['pan', 'manzana', 'pera', 'durazno', 'uva'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'pollo', 'papas', 'zanahoria', 'cebolla', 'pan'],
  ['pan', 'fideos', 'leche' , 'arroz', 'azúcar', 'salsa', 'albahaca', 'queso'],
  ['pan', 'helado', 'chocolate', 'nuez', 'caramelo'],
  ['pan', 'hamburguesa', 'agua', 'limón', 'azúcar', 'hielo', 'pan'],
  ['pan', 'café', 'leche' , 'arroz', 'azúcar', 'canela'],
  ['pan', 'naranja', 'zanahoria', 'jengibre', 'limón'],
  ['pan', 'arroz', 'frijoles', 'plátano', 'queso'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pescado', 'limón', 'sal', 'pimienta'],
  ['pan', 'brócoli', 'leche' , 'arroz', 'azúcar', 'coliflor', 'zanahoria', 'papas'],
  ['pan', 'avena', 'leche' , 'arroz', 'miel', 'almendras', 'pan'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'hamburguesa', 'sandía', 'melón', 'fresa', 'kiwi'],
  ['pan', 'hamburguesa', 'pan', 'lechuga', 'tomate'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'mayonesa', 'mostaza'],
  ['pan', 'pimiento', 'leche' , 'arroz', 'azúcar', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'durazno', 'melocotón', 'ciruela', 'albaricoque', 'pan'],
  ['pan', 'espinacas', 'leche' , 'arroz', 'azúcar', 'ricota', 'nuez moscada', 'sal'],
  ['pan', 'hamburguesa', 'pistachos', 'almendras', 'nueces', 'anacardos'],
  ['pan', 'pimienta', 'comino', 'cúrcuma', 'paprika'],
  ['pan', 'fresa', 'plátano', 'yogur', 'miel'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'maní', 'pasas', 'nuez', 'almendra'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'té', 'limón', 'miel', 'menta'],
  ['pan', 'hamburguesa', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'papas', 'leche' , 'arroz', 'azúcar', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz', 'pan'],
  ['pan', 'hamburguesa', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'carne','pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'pollo', 'leche' , 'arroz', 'azúcar', 'limón', 'ajo', 'romero'],
  ['pan', 'yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso', 'pan'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'avena', 'canela'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'nuez', 'miel', 'canela'],
  ['pan', 'carne','yogur', 'frutilla', 'avena', 'miel'],
  ['pan', 'pavo', 'pan', 'lechuga', 'tomate'],
  ['pan', 'pimiento', 'cebolla', 'tomate', 'ajo'],
  ['pan', 'carne','fresa', 'leche' , 'arroz', 'azúcar', 'plátano', 'yogur', 'miel'],
  ['pan', 'leche' , 'arroz', 'azúcar', 'té', 'limón', 'miel', 'menta', 'pan'],
  ['pan', 'azúcar', 'zanahoria', 'apio', 'pepino', 'remolacha'],
  ['pan', 'hamburguesa', 'papas', 'huevo', 'mayonesa', 'mostaza'],
  ['pan', 'calabaza', 'zanahoria', 'batata', 'maíz'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'garbanzos', 'limón', 'aceite de oliva', 'comino'],
  ['pan', 'carne','pasta', 'atún', 'tomate', 'aceitunas'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'pollo', 'limón', 'ajo', 'romero'],
  ['pan', 'frijoles', 'arroz', 'plátano', 'queso'],
  ['pan', 'nuez', 'miel', 'avena', 'leche' , 'arroz', 'azúcar', 'canela', 'pan'],
  ['pan', 'carne','nuez', 'miel', 'avena', 'canela', 'leche' , 'arroz', 'azúcar', 'pan'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'hamburguesa', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'nuez', 'miel', 'canela'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'carne','manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'carne','manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'carne','hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'carne','hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'carne','pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'carne','pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'carne','pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'lechuga', 'zanahoria', 'remolacha', 'pepino'],
  ['pan', 'carne','pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'carne','pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'carne','pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'carne','hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  ['pan', 'pan', 'huevos', 'café', 'arroz'],
  ['pan', 'hamburguesa', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'manzana', 'leche' , 'arroz', 'pan', 'huevos', 'jugo'],
  ['pan', 'manzana', 'pan', 'huevos', 'café'],
  ['pan', 'manzana', 'leche' , 'arroz', 'azúcar', 'huevos'],
  ['pan', 'hamburguesa', 'manzana', 'arroz', 'pollo', 'pasta', 'salsa'],
  ['pan', 'manzana', 'plátano', 'naranja', 'pera'],
  ['pan', 'hamburguesa', 'pasta', 'tomate', 'queso', 'espinacas'],
  ['pan', 'carne', 'pimienta', 'sal', 'cebolla'],
  //   // Más productos...
];
